//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.12 at 05:06:14 PM MSK 
//


package beans.models;

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

import static beans.soap.UserEndpoint.NAMESPACE_URI;

@XmlRootElement(namespace = NAMESPACE_URI)
public class GetUser
{
    private String email;

    /**
     * Gets the value of the email property.
     *
     * @return possible object is
     * {@link String }
     */
    @XmlElement
    public String getEmail()
    {
        return email;
    }

    /**
     * Sets the value of the email property.
     *
     * @param value allowed object is
     * {@link String }
     */
    public void setEmail(String value)
    {
        this.email = value;
    }

}
